{
 "title": "Summary row",
 "panels": [
  {
   "title": "Status",
   "gridPos": { "w": 4, "h": 5 },
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"vector_search\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "# Indexes",
   "gridPos": { "w": 3, "h": 5 },
   "targets": [
    {
     "expr": "max(count(index_size{job=\"vector_search\", instance=~\"$node\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sum(node_filesystem_size_bytes{job=\"vector_search_os\", instance=~\"$node\"} - node_filesystem_avail_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by (instance, cluster))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(sum(node_filesystem_avail_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by (instance))",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(sum(node_filesystem_size_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by (instance, cluster) -sum(node_filesystem_avail_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by (instance, cluster)) by ([[by]])"
    }
   ]
  },
  {
   "title": "CPU",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*avg(sum(rate(node_cpu_seconds_total{job=\"vector_search_os\", mode!~\"idle\", instance=~\"$node\"}[1m])) by(cpu)) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memory % Usage",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-avg(node_memory_MemAvailable_bytes{job=\"vector_search_os\", instance=~\"$node\"})/avg(node_memory_MemTotal_bytes{job=\"vector_search_os\", instance=~\"$node\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"vector_search_os\", instance=~\"$node\"} - node_memory_MemAvailable_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "OS Information",
 "panels": [
  {
   "title": "Disk Usage by [[by]]",
   "description": "Average Disk Usage",
   "gridPos": { "h": 12, "w": 6 },
   "targets": [
    {
     "expr": "avg(sum(node_filesystem_size_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by (cluster, dc, instance, rack)-sum(node_filesystem_avail_bytes{job=\"vector_search_os\", instance=~\"$node\"})by (cluster, dc, instance, rack)) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memory Usage by [[by]]",
   "description": "Average Disk Usage",
   "gridPos": { "h": 12, "w": 6 },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"vector_search_os\", instance=~\"$node\"}-node_memory_MemAvailable_bytes{job=\"vector_search_os\", instance=~\"$node\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "CPU Usage by [[by]]",
   "description": "Average CPU Usage",
   "gridPos": { "h": 12, "w": 6 },
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode != \"idle\", instance=~\"$node\"}[1m])) by (cluster, cpu, instance)) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "Index Row",
 "panels": [
  {
   "title": "Index Size",
   "targets": [
    {
     "expr": "avg(index_size{index_name=\"$index\", instance=~\"$node\"}) by ([[by]])",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "Index build rate",
   "targets": [
    {
     "expr": "avg(rate(index_size{index_name=\"$index\", instance=~\"$node\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "Index requests rate",
   "targets": [
    {
     "expr": "avg(rate(request_latency_seconds_count{index_name=\"$index\", instance=~\"$node\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "{{instance}} {{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "targets": [
    {
     "expr": "avg(rate(request_latency_seconds_sum{index_name=\"$index\", instance=~\"$node\"}[$__rate_interval])/rate(request_latency_seconds_count{index_name=\"$index\", instance=~\"$node\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "{{instance}} {{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{index_name=\"$index\", instance=~\"$node\"}[$__rate_interval])) by ([[by]], keyspace,index_name, le))",
     "legendFormat": "{{instance}} {{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_seconds_bucket{index_name=\"$index\", instance=~\"$node\"}[$__rate_interval])) by ([[by]], keyspace,index_name, le))",
     "legendFormat": "{{instance}} {{keyspace}} {{index_name}}"
    }
   ]
  }
 ]
}