{
 "title": "New row",
 "panels": [
  {
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">CQL By User - Coordinator</h1>"
   }
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "CQL Insert by [[by]]",
   "description": "Number of CQL INSERT commands generated by the user\n\nscylla_cql_inserts",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_inserts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) - sum(rate(scylla_cql_inserts_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Reads by [[by]]",
   "description": "Number of CQL SELECT commands generated by the user",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) - sum(rate(scylla_cql_reads_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Deletes by [[by]]",
   "description": "Number of CQL DELETE commands generated by the user\n\nscylla_cql_deletes",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_deletes{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])-sum(rate(scylla_cql_deletes_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Updates by [[by]]",
   "description": "Number of CQL UPDATE commands generated by the user\n\nscylla_cql_updates",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_updates{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])-sum(rate(scylla_cql_updates_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Client CQL connections by [[by]]",
   "description": "amount of CQL connections currently established",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(scylla_transport_current_connections{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Client CQL new connections by [[by]]",
   "description": "Rate of CQL connections created",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_transport_cql_connections{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "BYPASS CACHE",
   "description": "Counts the number of SELECT statements with BYPASS CACHE option",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_select_bypass_caches{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Errors by [[by]]",
   "description": "CQL errors by type, only active errors are shown",
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_cql_errors_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]],type) >0"
    }
   ]
  },
  {
   "title": "CQL Unlogged Batches by [[by]]",
   "description": "Number of CQL batches command, each batched command is counted once.\n\nIs generally used to group mutations for a single partition and do not suffer from the performance penalty imposed by logged batches, but there is no atomicity guarantee for multi-partition updates.",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_batches_pure_unlogged{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Command In Batches by [[by]]",
   "description": "Number of CQL command batched. Each batch would add the number of commands inside the batch",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_statements_in_batches{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Row Reads by [[by]]",
   "description": "Number of CQL row reads",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_rows_read{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Secondary indexes Reads by [[by]]",
   "description": "Number of reads using secondary indexes",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_secondary_index_reads{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Requests by Consistency Level by [[by]]",
   "description": "Requests by Consistency Level",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])>0) by ([[by]], consistency_level))"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "options": {
    "content": "<span style=\"color:#5780C1;font-size: 2rem;\">CQL System tables</span></br><span style=\"\">The following information is based on Scylla Plugin configuration, check the </span><a target=\"_blank\" herf=\"https://monitoring.docs.scylladb.com/stable/install/monitor-without-docker.html#using-scylla-plugin-with-grafana\" onclick=\"window.open('https://monitoring.docs.scylladb.com/stable/install/monitor-without-docker.html#using-scylla-plugin-with-grafana', '_blank')\">documentation</a><span> for more details on how to enable it.</span>"
   }
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">CQL Internal - Coordinator</h1>"
   }
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "CQL Internal Insert",
   "description": "Number of CQL INSERT commands generated by internal operations",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_inserts_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Internal Reads",
   "description": "Number of CQL SELECT commands generated by internal operations",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_reads_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Deletes",
   "description": "Number of CQL DELETE commands generated by internal operations\n\nscylla_cql_deletes",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_deletes_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Updates",
   "description": "Number of CQL UPDATE commands generated by internal operations\n\nscylla_cql_updates",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_updates_per_ks{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", who=\"internal\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">LWT</h1>"
   }
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "CQL Insert",
   "description": "scylla_cql_inserts",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_inserts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", conditional=\"yes\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Deletes",
   "description": "scylla_cql_deletes",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_deletes{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", conditional=\"yes\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Updates",
   "description": "scylla_cql_updates",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_updates{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", conditional=\"yes\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "CQL Batches by [[by]]",
   "description": "Number of CQL batches command, each batched command is counted once",
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_cql_batches{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", conditional=\"yes\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Optimization</h1>"
   }
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "CQL Non-Prepared Statements",
   "description": "All of the requests should be prepared\n\nPrepared statements remove the overhead of parsing the query every time and allow optimal routing of requests from client to server",
   "targets": [
    {
     "expr": "floor(100 *sum(cql:non_system_prepared1m)/ (sum(cql:all_shardrate1m{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) - sum(cql:all_system_shardrate1m{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}))) OR vector(0)"
    }
   ]
  },
  {
   "title": "CQL Non-Prepared Statements",
   "description": "All of the requests should be prepared\n",
   "targets": [
    {
     "expr": "sum(cql:non_system_prepared1m{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "description": "All requests should be paged\n\nNon Paged request sources:\n- Client modifying the fetch size\n\nNon Paged requests require reading all the results and returning them in a single request.",
   "targets": [
    {
     "expr": "100 * ((sum(rate(scylla_cql_unpaged_select_queries{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))-sum(rate(scylla_cql_unpaged_select_queries_per_ks{ks=\"system\",instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])))/sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))) OR vector(0)"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "description": "Non-Paged requests require reading all the results and returning them in a single request",
   "targets": [
    {
     "expr": "sum(rate(scylla_cql_unpaged_select_queries{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])-sum(rate(scylla_cql_unpaged_select_queries_per_ks{ks=\"system\",instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Non-Token Aware",
   "description": "All of the requests should be Token Aware\n\nNon Token Aware requests sources:\n* Non-Prepared Stamements\n* Client not using a Token Aware load balancing policy\n\nTokenAware requests are sent to a Scylla node that is also a replica. Token Un-Aware requests require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "targets": [
    {
     "expr": "clamp_max(100*((sum(rate(scylla_storage_proxy_coordinator_reads_coordinator_outside_replica_set{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or on() vector(0)) + (sum(rate(scylla_storage_proxy_coordinator_writes_coordinator_outside_replica_set{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or on() vector(0)))/((sum(rate(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) + 1) or vector(1)),100) OR vector(0)"
    }
   ]
  },
  {
   "title": "Non-Token Aware Queries",
   "description": "Requests that are not token aware indicates that requests are not routed to the right node, which require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_reads_coordinator_outside_replica_set{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or on() sum(scylla_reactor_utilization*0) by([[by]]))",
     "legendFormat": "Reads {{dc}} {{instance}} {{shard}}"
    },
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_writes_coordinator_outside_replica_set{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or on() sum(scylla_reactor_utilization*0) by([[by]]))",
     "legendFormat": "Writes {{dc}} {{instance}} {{shard}}"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Reversed CQL Reads",
   "description": "Reversed CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with ORDER BY that is different from the \"CLUSTERING ORDER BY\" of the table\nAlternatives:\n\n* Denormalize your data (use a Materialized View)",
   "targets": [
    {
     "expr": "100 * sum(rate(scylla_cql_reverse_queries{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) / sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "description": "Reversed CQL Reads entail additional processing on server side and should be avoided",
   "targets": [
    {
     "expr": "sum(rate(scylla_cql_reverse_queries{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "description": "ALLOW FILTERING CQL Reads, the percentage of read requests with 'ALLOW FILTERING'\n\nALLOW FILTERING CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned - check \n\"ALLOW FILTERING CQL Read Filtered Rows to check what percentage of the data is used\"\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "targets": [
    {
     "expr": "100 * sum(rate(scylla_cql_filtered_read_requests{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) / sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "description": "Read requests with ALLOW FILTERING\n\nALLOW FILTERING CQL Reads entail additional processing on server side and should be avoided",
   "targets": [
    {
     "expr": "sum(rate(scylla_cql_filtered_read_requests{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING Filtered Rows",
   "description": "ALLOW FILTERING Filtered rows, the percentage of rows that were read and then filtered.\n\nALLOW FILTERING CQL Reads entail additional processing on server side. \nReading a row and then filter it is a waste of resources.\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "targets": [
    {
     "expr": "100 * sum(rate(scylla_cql_filtered_rows_dropped_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))  /sum(rate(scylla_cql_filtered_rows_read_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Read Filtering",
   "description": "CQL Queries with ALLOW FILTERING should be avoided.\nDropped rows are rows that were read but were filtered by the server.\nWhen dropped rows is relatively high you should consider the alternatives",
   "targets": [
    {
     "expr": "sum(rate(scylla_cql_filtered_rows_read_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "rows read $node $shard"
    },
    {
     "expr": "sum(rate(scylla_cql_filtered_rows_matched_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "rows matched $node $shard"
    },
    {
     "expr": "sum(rate(scylla_cql_filtered_rows_dropped_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "rows dropped $node $shard"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Cross DC Information</h1><h5>This section is relevant only if you have more than one DC</h5>"
   }
  }
 ]
}