unset SUPPORTED_VERSIONS
unset MANAGER_SUPPORTED_VERSIONS
unset DEFAULT_VERSION
unset MANAGER_DEFAULT_VERSION
declare -A SUPPORTED_VERSIONS
declare -A MANAGER_SUPPORTED_VERSIONS
declare -A DEFAULT_VERSION
declare -A MANAGER_DEFAULT_VERSION
SUPPORTED_VERSIONS["3.8"]="4.3,4.4,4.5,2020.1,2021.1"
MANAGER_SUPPORTED_VERSIONS["3.8"]="2.3"
DEFAULT_VERSION["3.8"]="4.4"
MANAGER_DEFAULT_VERSION["3.8"]="2.3"
