unset SUPPORTED_VERSIONS
unset MANAGER_SUPPORTED_VERSIONS
unset DEFAULT_VERSION
unset MANAGER_DEFAULT_VERSION
unset DEFAULT_ENTERPRISE_VERSION
declare -A SUPPORTED_VERSIONS
declare -A MANAGER_SUPPORTED_VERSIONS
declare -A DEFAULT_VERSION
declare -A MANAGER_DEFAULT_VERSION
declare -A DEFAULT_ENTERPRISE_VERSION
SUPPORTED_VERSIONS["3.8"]="4.3,4.4,4.5,2020.1,2021.1"
MANAGER_SUPPORTED_VERSIONS["3.8"]="2.3"
DEFAULT_VERSION["3.8"]="4.4"
DEFAULT_ENTERPRISE_VERSION["3.8"]="2020.1"
MANAGER_DEFAULT_VERSION["3.8"]="2.3"
MANAGER_DEFAULT_VERSION["master"]="2.3"
PROMETHEUS_VERSION=v2.27.1
ALERT_MANAGER_VERSION="v0.22.1"
GRAFANA_VERSION=7.5.7
LOKI_VERSION="2.2.1"
GRAFANA_RENDERER_VERSION="2.1.1"