#!/usr/bin/bash
print_usage() {
    echo "install_python [--os centos/ubuntu]"
    exit 1
}
OS="centos"
while [ $# -gt 0 ]; do
    case "$1" in
        "--os")
            OS="$2"
            shift 2
            ;;
        *)
            print_usage
            ;;
    esac
done
if [ "$OS" = "ubuntu" ]; then
    sudo apt-get install -y python3-setuptools
    sudo apt-get install -y python3-pip
    exit 0
fi

yum -y groupinstall 'Development Tools'
yum -y install openssl-devel bzip2-devel libffi-devel
yum remove -y python3
curl -O https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tgz
tar -xzf Python-3.8.10.tgz
rm Python-3.8.10.tgz
cd Python-3.8.10
./configure --enable-optimizations
make altinstall
cd ..
rm -rf Python-3.8.10 
ln -s /usr/local/bin/python3.8 /usr/bin/python3
ln -s /usr/local/bin/pip3.8 /usr/bin/pip3
/usr/local/bin/python3.8 -m pip install --upgrade pip
