#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2018 ScyllaDB
#

#
# This file is part of Scylla.
#
# Scylla is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Scylla is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Scylla.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import shlex
import subprocess
from scylla_util import *
import argparse

VERSION='1.11.1-2'

def run(cmd):
    subprocess.check_call(shlex.split(cmd))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Download and install prometheus node_exporter')
    parser.add_argument('-F', '--force', action='store_true', default=False, help='Force re-installation when node_exporter is already installed')
    parser.add_argument('--arch', default='amd64', help='Architecture to use (amd64/arm64)')
    args = parser.parse_args()
    force = args.force
    arch = args.arch
    if not is_nonroot() and os.getuid() > 0:
        print('Requires root permission.')
        sys.exit(1)
    node_exporter_p = bindir_p() / 'node_exporter'
    if node_exporter_p.exists() or (bindir_p() / 'prometheus-node_exporter').exists():
        if force:
            print('node_exporter already installed, reinstalling')
            try:
                node_exporter = systemd_unit('node-exporter.service')
                node_exporter.stop()
            except Exception as e:
                print("could not create node-exporter.service file", e)
        else:
            print('node_exporter already installed, you can use `--force` to force reinstallation')
            sys.exit(1)

    if is_gentoo():
        run('emerge -uq app-metrics/node_exporter')
        print('app-metrics/node_exporter does not install systemd service files, please fill a bug if you need them.')
        sys.exit(1)
    else:
        deb_file = '/var/tmp/scylla-node-exporter_{version}_{arch}.deb'.format(version=VERSION, arch=arch)
        data = curl('https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/node-exporter/deb/scylla-node-exporter_{version}_{arch}.deb'.format(
            version=VERSION, arch=arch), byte=True)
        with open(deb_file, 'wb') as f:
            f.write(data)
        run('dpkg -i {deb}'.format(deb=deb_file))
        os.remove(deb_file)

    print('node_exporter successfully installed')
