#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2018 ScyllaDB
#

#
# This file is part of Scylla.
#
# Scylla is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Scylla is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Scylla.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import grp
import pwd
import shlex
import subprocess
from pathlib import Path
from scylla_util import *
import argparse

VERSION='1.11.1-2'
# The node_exporter binary is taken from the scylla-node-exporter deb, but the
# deb is extracted rather than installed with dpkg: registering the package
# (version 1:1.11.1-2, with an epoch) in dpkg would block installing Scylla on
# the same machine, because scylla depends on scylla-node-exporter with an
# exact epoch-0 version pin and apt refuses to downgrade across the epoch.
# SCT installs Scylla + Scylla Manager on top of the monitoring image, so the
# scylla-node-exporter package name must stay unclaimed, and our binary and
# unit must live in paths a real scylla-node-exporter install does not own.
NODE_EXPORTER_DIR = Path('/opt/node_exporter')
NODE_EXPORTER_BIN = NODE_EXPORTER_DIR / 'node_exporter'
NODE_EXPORTER_BIN_IN_DEB = 'opt/scylladb/node_exporter/node_exporter'
NODE_EXPORTER_SERVICE = 'node-exporter.service'
NODE_EXPORTER_USER = 'nodeexporter'

def run(cmd):
    subprocess.check_call(shlex.split(cmd))

def ensure_user(user):
    """Create the dedicated system user/group node-exporter.service runs as."""
    try:
        grp.getgrnam(user)
    except KeyError:
        run('groupadd --system {user}'.format(user=user))
    try:
        pwd.getpwnam(user)
    except KeyError:
        run('useradd --system --gid {user} --no-create-home --shell /usr/sbin/nologin {user}'.format(user=user))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Download and install prometheus node_exporter')
    parser.add_argument('-F', '--force', action='store_true', default=False, help='Force re-installation when node_exporter is already installed')
    parser.add_argument('--arch', default='amd64', help='Architecture to use (amd64/arm64)')
    args = parser.parse_args()
    force = args.force
    arch = args.arch
    if not is_nonroot() and os.getuid() > 0:
        print('Requires root permission.')
        sys.exit(1)
    if NODE_EXPORTER_BIN.exists() or (bindir_p() / 'node_exporter').exists() or (bindir_p() / 'prometheus-node_exporter').exists():
        if force:
            print('node_exporter already installed, reinstalling')
            try:
                node_exporter = systemd_unit(NODE_EXPORTER_SERVICE)
                node_exporter.stop()
            except Exception as e:
                print("could not stop {}".format(NODE_EXPORTER_SERVICE), e)
        else:
            print('node_exporter already installed, you can use `--force` to force reinstallation')
            sys.exit(1)

    if is_gentoo():
        run('emerge -uq app-metrics/node_exporter')
        print('app-metrics/node_exporter does not install systemd service files, please fill a bug if you need them.')
        sys.exit(1)
    else:
        deb_file = '/var/tmp/scylla-node-exporter_{version}_{arch}.deb'.format(version=VERSION, arch=arch)
        data = curl('https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/node-exporter/deb/scylla-node-exporter_{version}_{arch}.deb'.format(
            version=VERSION, arch=arch), byte=True)
        with open(deb_file, 'wb') as f:
            f.write(data)
        extract_dir = '/var/tmp/scylla-node-exporter-extract'
        run('rm -rf {dir}'.format(dir=extract_dir))
        run('dpkg-deb -x {deb} {dir}'.format(deb=deb_file, dir=extract_dir))
        run('install -d {dir}'.format(dir=NODE_EXPORTER_DIR))
        run('install -m 755 {src} {dst}'.format(
            src=os.path.join(extract_dir, NODE_EXPORTER_BIN_IN_DEB), dst=NODE_EXPORTER_BIN))
        run('rm -rf {dir}'.format(dir=extract_dir))
        os.remove(deb_file)
        ensure_user(NODE_EXPORTER_USER)
        unit_src = Path(__file__).resolve().parent / NODE_EXPORTER_SERVICE
        run('install -m 644 {src} /etc/systemd/system/{service}'.format(
            src=unit_src, service=NODE_EXPORTER_SERVICE))
        run('systemctl daemon-reload')
        node_exporter = systemd_unit(NODE_EXPORTER_SERVICE)
        node_exporter.enable()
        node_exporter.restart()
        if node_exporter.is_active().strip() != 'active':
            print('{} failed to start'.format(NODE_EXPORTER_SERVICE))
            sys.exit(1)

    print('node_exporter successfully installed')
