{
 "title": "New row",
 "panels": [
  {
   "title": "Requests/s",
   "gridPos": { "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_requests_served{cluster=~\"$cluster|$^\", dc=~\"$dc\"}[60s])) + (sum(rate(scylla_thrift_served{cluster=~\"$cluster|$^\", dc=~\"$dc\"}[60s])) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Avg Write",
   "description": "Average Write Latency",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(wlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)"
    }
   ]
  },
  {
   "title": "95% Write",
   "description": "99% write Latency",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(wlatencyp95{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)"
    }
   ]
  },
  {
   "title": "99% Write",
   "description": "99% write Latency",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(wlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)"
    }
   ]
  },
  {
   "title": "Avg Read",
   "description": "Average Read Latency",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)"
    }
   ]
  },
  {
   "title": "95% Read",
   "description": "99% read Latency",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rlatencyp95{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)"
    }
   ]
  },
  {
   "title": "99% Read",
   "description": "99% read Latency",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)"
    }
   ]
  },
  {
   "title": "Load",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{cluster=~\"$cluster|$^\", dc=~\"$dc\"} )"
    }
   ]
  },
  {
   "title": "R Failed",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_reads_failed{cluster=~\"$cluster|$^\", dc=~\"$dc\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "W Failed",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_writes_failed{cluster=~\"$cluster|$^\", dc=~\"$dc\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Timeouts",
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_timeouts{cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Advisor</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information for $dc</h1>"
  }
 ]
}