{
 "title": "Summary row",
 "panels": [
  {
   "title": "Manager",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla_manager\"}==0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "targets": [
    {
     "expr": "count(scylla_manager_healthcheck_cql_rtt_ms{cluster=~\"$cluster|$^\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "CQL Fail",
   "description": "The number of nodes that Scylla manager CQL probe failed connecting to. It could indicate a network or a node problem",
   "targets": [
    {
     "expr": "count(scylla_manager_healthcheck_cql_status{cluster=~\"$cluster|$^\"}==-1) OR vector(0)",
     "legendFormat": "Nodes without CQL connection"
    }
   ]
  },
  {
   "title": "Repair",
   "gridPos": { "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg(scylla_manager_repair_progress{cluster=~\"[[cluster]]\", instance=\"\", keyspace=\"\"}) by (task) * sum(scylla_manager_task_active_count{cluster=~\"[[cluster]]\", type=\"repair\"}) by (task))  or vector(0)"
    }
   ]
  },
  {
   "title": "Last repair",
   "description": "The time of the last successful repair",
   "gridPos": { "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "manager:repair_done_ts{cluster=\"$cluster\"}*1000"
    }
   ]
  },
  {
   "title": "Last Failure",
   "description": "The time of the last failed repair",
   "gridPos": { "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "manager:repair_fail_ts{cluster=\"$cluster\"}*1000"
    }
   ]
  },
  {
   "title": "Backup",
   "gridPos": { "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg(scylla_manager_backup_percent_progress{cluster=~\"[[cluster]]\", instance=\"\", keyspace=\"\"}) by (task) * sum(scylla_manager_task_active_count{cluster=~\"[[cluster]]\", type=\"backup\"}) by (task)) or vector(0)"
    }
   ]
  },
  {
   "title": "Last Backup",
   "description": "The time of the last successful backup",
   "gridPos": { "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "manager:backup_done_ts{cluster=\"$cluster\"}*1000"
    }
   ]
  },
  {
   "title": "Last Failure",
   "description": "The time of the last failed backup",
   "gridPos": { "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "manager:backup_fail_ts{cluster=\"$cluster\"}*1000"
    }
   ]
  }
 ]
}
{
 "title": "Repair rate Row",
 "panels": [
  {
   "title": "Repair Segments Rate",
   "targets": [
    {
     "expr": "sum(rate(scylla_manager_repair_segments_success{cluster=~\"[[cluster]]\", instance=~\"$instance\", shard=~\"$shard\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Repair Segments Error Rate",
   "targets": [
    {
     "expr": "sum(rate(scylla_manager_repair_segments_error{cluster=~\"[[cluster]]\", instance=~\"$instance\", shard=~\"$shard\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "SSH connection Row",
 "panels": [
  {
   "title": "SSH open connections by $by",
   "description": "The number of SSH connection used by the manager",
   "targets": [
    {
     "expr": "sum(scylla_manager_ssh_open_streams_count{instance=~\"$instance\"}) by ($by)"
    }
   ]
  },
  {
   "title": "CQL probe duration by $by",
   "description": "Average duration time for a CQL ping operation",
   "targets": [
    {
     "expr": "avg(scylla_manager_healthcheck_cql_rtt_ms{instance=~\"$instance\", cluster=~\"[[cluster]]\"}) by ($by)"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Manager Agent</h1>"
  }
 ]
}
{
 "title": "SSH connection Row",
 "panels": [
  {
   "title": "Agent Memory Heap usage",
   "description": "An increase in memory can indicate an issue with the Manager agent",
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"manager_agent.?\", instance=~\"$instance\"}) by ($by)"
    }
   ]
  },
  {
   "title": "Agent Threads",
   "description": "An increase in the number of threads can indicate an issue with the Manager agent",
   "targets": [
    {
     "expr": "avg(go_threads{job=~\"manager_agent.?\", instance=~\"$instance\"}) by ($by)"
    }
   ]
  }
 ]
}