{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Compactions I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_compaction_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_query_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_commitlog_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_memtable_flush_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_read_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_write_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  }
 ]
}