{
 "title": "New row",
 "panels": [
  {
   "title": "Load",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Requests Served per [[by]] - Coordinator",
   "description": "Amount of requests served as the coordinator. Imbalances here represent dispersion at the connection level, not your data model.",
   "targets": [
    {
     "expr": "$func(rate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) + $func(rate(scylla_thrift_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Reads per [[by]] - Replica",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes per [[by]] - Replica",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_writes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Reads and Writes - Coordinator</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Foreground Writes per [[by]]",
   "description": "Foreground writes are writes that weren't acknowledged yet to the application. For instance, if a single replica responded and two are needed due to the consistency level. This metric represents a queue size, not a rate. High values here correlate with increased write latencies.",
   "targets": [
    {
     "expr": "$func(scylla_storage_proxy_coordinator_foreground_writes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Foreground Reads per [[by]]",
   "description": "Foreground reads are reads that weren't acknowledged yet to the application. For instance, if a single replica responded and two are needed due to the consistency level. This metric represents a queue size, not a rate. High values here correlate with increased read latencies.",
   "targets": [
    {
     "expr": "$func(scylla_storage_proxy_coordinator_foreground_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Average write latency by [[by]]",
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]])/($func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]]) + 1)"
    }
   ]
  },
  {
   "title": "Average read latency by [[by]]",
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]])/($func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]]) + 1)"
    }
   ]
  },
  {
   "title": "95th percentile write latency by [[by]]",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile write latency by [[by]]",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "95th percentile read latency by [[by]]",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile read latency by [[by]]",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by ([[by]], le))"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Background Writes per [[by]]",
   "description": "Background writes are writes that are already acknowledged to the application but have additional work to be done. For instance, if a replica responded and only one is needed, this request is still listed as a background request until all replicas respond. This metric represents a queue size, not a rate. High values here correlate with increased write latencies.",
   "targets": [
    {
     "expr": "$func(scylla_storage_proxy_coordinator_background_writes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Reads per [[by]]",
   "description": "Background reads are reads that are already acknowledged to the application but have additional work to be done. For instance, if a replica responded and only one is needed, this request is still listed as a background request until all replicas respond. This metric represents a queue size, not a rate. High values here correlate with increased read latencies.",
   "targets": [
    {
     "expr": "$func(scylla_storage_proxy_coordinator_background_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Hints Written per [[by]]",
   "targets": [
    {
     "expr": "$func(rate(scylla_hints_manager_written{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Hints sent per [[by]]",
   "targets": [
    {
     "expr": "$func(rate(scylla_hints_manager_sent{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Speculative Digest Reads By [[by]]",
   "description": "Number of times a digest read was done on behalf of a speculative retry.\n\nSpeculative retry is a mechanism that causes the client or server to speculate that a request may fail, and send a new request.\n\nspeculative retry may reduce latency in exchange for system load, but only if there is little activity.\n\nA lot of speculative retries increases load and can harm latency more than helping.",
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_speculative_digest_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Speculative Data Reads By [[by]]",
   "description": "Number of times a read was done on behalf of a speculative retry.\n\nSpeculative retry is a mechanism that causes the client or server to speculate that a request may fail, and send a new request.\n\nspeculative retry may reduce latency in exchange for system load, but only if there is little activity.\n\nA lot of speculative retries increases load and can harm latency more than helping.",
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_speculative_data_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts and Errors - Coordinator</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Active sstable reads",
   "description": "The number of currently active read operations",
   "targets": [
    {
     "expr": "$func(scylla_database_active_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Queued sstable reads",
   "description": "number of currently queued read operations",
   "targets": [
    {
     "expr": "$func(scylla_database_queued_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes currently blocked on dirty",
   "description": "The current number of requests blocked due to reaching the memory quota. Non-zero value indicates that our bottleneck is memory",
   "targets": [
    {
     "expr": "$func(scylla_database_requests_blocked_memory_current{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes currently blocked on commitlog",
   "description": "number of currently pending allocations. A non-zero value indicates that we have a bottleneck in the disk write flow.",
   "targets": [
    {
     "expr": "$func(scylla_commitlog_pending_allocations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Reciprocal Miss Rate (HWLB)",
   "description": "Reciprocal Miss Rate is a score in the range of 1 to 100 that is used to decide the fraction of read requests to send to each replica - a replica with twice the RMR value of another replica will serve twice the number of read requests.\n\nRMR is calculated on a table level, this is an aggregate estimation of that score.",
   "targets": [
    {
     "expr": "clamp_max(1 + sum(rate(scylla_cache_row_hits[1m])) by ([[by]])/(sum(rate(scylla_cache_row_misses[1m])) by ([[by]]) + 0.00001),100)"
    }
   ]
  },
  {
   "title": "Reads failed",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_reads_failed{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes blocked on dirty",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_requests_blocked_memory{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes blocked on commitlog",
   "targets": [
    {
     "expr": "$func(rate(scylla_commitlog_requests_blocked_memory{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {},
  {},
  {
   "title": "Writes failed",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_writes_failed{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes timed out",
   "targets": [
    {
     "expr": "$func(rate(scylla_database_total_writes_timedout{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache - Replica</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Row Hits",
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_row_hits{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Hits",
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_partition_hits{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Misses",
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_row_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Misses",
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_partition_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Rows",
   "targets": [
    {
     "expr": "$func(scylla_cache_rows{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partitions",
   "targets": [
    {
     "expr": "$func(scylla_cache_partitions{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Used Bytes",
   "targets": [
    {
     "expr": "$func(scylla_cache_bytes_used{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "targets": [
    {
     "expr": "$func(scylla_cache_bytes_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Materialized Views - Replica</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">LWT - Coordinator</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CDC - Replica</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Memory - Replica</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "LSA total memory",
   "targets": [
    {
     "expr": "$func(scylla_lsa_total_space_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Non-LSA used memory",
   "targets": [
    {
     "expr": "$func(scylla_lsa_non_lsa_used_space_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Compaction - Replica</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Running Compactions",
   "targets": [
    {
     "expr": "$func(scylla_compaction_manager_compactions{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions CPU Runtime",
   "description": "Percentage of CPU time used by compaction",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "($func(rate(scylla_scheduler_runtime_ms{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\", group=\"compaction\"}[$__rate_interval])) by ([[by]]))/10"
    }
   ]
  },
  {
   "title": "Compactions Shares",
   "description": "Shares assigned to the compaction",
   "targets": [
    {
     "expr": "avg(scylla_scheduler_shares{group=\"compaction\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  }
 ]
}