{
 "title": "Summary row",
 "panels": [
  {
   "title": "Status",
   "gridPos": { "w": 4, "h": 5 },
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"vector_store\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "# Indexes",
   "gridPos": { "w": 3, "h": 5 },
   "targets": [
    {
     "expr": "count(index_size{job=\"vector_store\"})"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"vector_store_os\"}) - sum(node_filesystem_avail_bytes{job=\"vector_store_os\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{job=\"vector_store_os\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"vector_store_os\"})-sum(node_filesystem_avail_bytes{job=\"vector_store_os\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*avg(sum(rate(node_cpu_seconds_total{job=\"vector_store_os\", mode!~\"idle\"}[1m])) by(cpu))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "gridPos": { "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"vector_store_os\"})-avg(node_memory_MemAvailable_bytes{job=\"vector_store_os\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}
{
 "title": "Index Row",
 "panels": [
  {
   "title": "Index Size",
   "targets": [
    {
     "expr": "index_size{index_name=\"$index\"}",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "Index build rate",
   "targets": [
    {
     "expr": "rate(index_size{index_name=\"$index\"}[$__rate_interval])",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "Index requests rate",
   "targets": [
    {
     "expr": "rate(request_latency_seconds_count{index_name=\"$index\"}[$__rate_interval])",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum{index_name=\"$index\"}[$__rate_interval])/rate(request_latency_seconds_count{index_name=\"$index\"}[$__rate_interval])",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{index_name=\"$index\"}[$__rate_interval])) by (keyspace,index_name, le))",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_seconds_bucket{index_name=\"$index\"}[$__rate_interval])) by (keyspace,index_name, le))",
     "legendFormat": "{{keyspace}} {{index_name}}"
    }
   ]
  }
 ]
}