{
 "title": "New row",
 "panels": [
  {
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Total Nodes",
   "targets": [
    {
     "expr": "count(up{job=\"scylla\", cluster=~\"$cluster|$^\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla\", cluster=~\"$cluster|$^\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "content": "##  " },
  {
   "title": "Total Requests",
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{cluster=~\"$cluster|$^\"}[60s])) + sum(irate(scylla_thrift_served{cluster=~\"$cluster|$^\"}[60s]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {}
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Load per [[by]]",
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Requests Served per [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]]) + sum(irate(scylla_thrift_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk Activity</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Disk Writes per Server",
   "targets": [
    {
     "expr": "sum(irate(node_disk_writes_completed_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Disk Reads per Server",
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Disk Writes Bps per Server",
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Disk Read Bps per Server",
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Compactions I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_compaction_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_query_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_commitlog_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_memtable_flush_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_read_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_write_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_operations{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}