{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Compactions I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"compaction\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"compaction\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"compaction\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"query\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"query\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"query\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"commitlog\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"commitlog\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"commitlog\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"memtable_flush\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"memtable_flush\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"memtable_flush\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"streaming_read\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"streaming_read\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"streaming_read\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"streaming_write\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"streaming_write\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"streaming_write\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}