version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosec
  settings:
    errcheck:
      check-type-assertions: true
    gosec:
      excludes:
        - G204 # subprocess launched with variable — acceptable for docker commands
  exclusions:
    paths:
      - testdata
