name: Sync new GitHub issues to Jira

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  sync-issue-to-jira:
    uses: scylladb/github-automation/.github/workflows/main_create_jira_issue_from_gh_issue.yml@main
    with:
      jira_project_key: "MONITOR"
    secrets:
      caller_jira_auth: ${{ secrets.USER_AND_KEY_FOR_JIRA_AUTOMATION }}